export const companyPhoneNumber = "020 4524 0108"
export const whatsappPhoneNumber = "079 4358 5365"
export const companyEmail = "mclevcompany@gmail.com"
export const companyAddress = "38 Marble House, Felspar close. SE18 1LN"
export const facebookPageUrl = "https://www.facebook.com/mclev.cleanings"
export const tiktokPageUrl = "https://www.tiktok.com/@mclevcleaning?_t=8ppl1KpJCL3&_r=1"